name: Create release
on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Release
        uses: ScientaNL/release-npm-github-action@1.2.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          npm-token: "${{ secrets.NPM_SCIENTA_TOKEN }}"
          repository-owner: "ScientaNL"
          npm-options: "{tag: 'latest', access: 'public'}"
